### ISSUE TITLE
Chapter_09 - After fixing Refresh Token loop

### ISSUE THREAD

**Issue by trapezoide** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#15]
Hello,
I applied the fix suggested at https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/8 to get rid of the loop. That took care of the infinite loop; I don't see any errors being logged in the console anymore. The problem I see now when I follow the steps mentioned under "Testing it up" on page 833 is that, after clicking the "Apply Changes" button and making the call to the API to update the quiz, the user is not redirected to the Home page as he should.  The html rendered by the quiz-edit.component.html file remains on the screen with the focus set on the "Apply Changes" button.

**Comment by dvanhussel** [comment]
Hi,
This happens because the initial call to the Web API returns status 401. This is handled in the 'on Error' part of the subscribe. You can see the error logged to the console (https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/blob/a4824202a0e795c7005511b98eef7d271e65be62/TestMakerFreeWebApp_Chapter_09/ClientApp/app/components/quiz/quiz-edit.component.ts#L92). The HTTP interceptor creates a new call to the Web API, but the onSubmit function in the quiz-edit component is not subscribed to this new call. So the navigation to route 'home' is not hit.

I'm not an expert (working through the book myself ;-) ) but I think this could be fixed in the interceptor. Navigate to route home after the Web API is successfully called with the new token. 
Of course that would do that for any request. If you don't want that, I think you could make the route a property of the request, so that the interceptor can check if a route should be activated.

If I'm wrong or someone has a better/cleaner solution , please correct me! :-)

**Comment by mattjones61** [comment]
I think the issue may be that the auth.response.interceptor, handleError routine makes a new separate call to http.request and therefore creates a separate, independent Observable. Doing this allows the original request to 'finish' before handleError returns.
I'm very new to this as well, but replacing the handleError code with something that does not make a separate call (and a separate Observable) seems to work. 
Note that as it's not a separate call, the request header needs to be updated with the new token before returning, otherwise it just uses the original and returns 401 again.
So maybe something like this (in auth.response.interceptor)…

```typescript
                .catch(error => {
//                  return this.handleError(error)
                    if (error instanceof HttpErrorResponse) {
                        if (error.status === 401) {
                            var previousRequest = this.currentRequest;
                            return this.auth.doRefreshToken()
                                .flatMap((refreshed) => {
                                    var token = (this.auth.isLoggedIn()) ? this.auth.getAuth()!.token : null;
                                    if (token) {
                                        previousRequest = previousRequest.clone({
                                            setHeaders: { Authorization: `Bearer ${token}` }
                                        });
                                        console.log("header token reset");
                                    }
                                    return next.handle(previousRequest);
                                });
                        } 
                    }
                    return Observable.throw(error);
                });
```

**Comment by haarlem-dvh** [comment]
Yes, this solution is a lot better! :-)

Based on @mattjones61 , I have updated intercept and handleError like this:

```
intercept(
        request: HttpRequest<any>,
        next: HttpHandler): Observable<HttpEvent<any>> {

        this.auth = this.injector.get(AuthService);
        var token = (this.auth.isLoggedIn()) ? this.auth.getAuth()!.token : null;

        if (token) {
            // save current request
            this.currentRequest = request;

            return next.handle(request)
                .do((event: HttpEvent<any>) => {
                    if (event instanceof HttpResponse) {
                        // do nothing
                    }
                })
                .catch(error => {
                    return this.handleError(error, next);
                });
        }
        else {
            return next.handle(request);
        }
    }

    handleError(error: any,next: HttpHandler) {
        if (error instanceof HttpErrorResponse) {
            if (error.status === 401) {
                var previousRequest = this.currentRequest;
                return this.auth.refreshToken()
                    .flatMap((refreshed) => {
                        var token = (this.auth.isLoggedIn()) ? this.auth.getAuth()!.token : null;
                        if (token) {
                            previousRequest = previousRequest.clone({
                                setHeaders: { Authorization: `Bearer ${token}` }
                            });
                            console.log("header token reset");
                        }
                        return next.handle(previousRequest);
                    });
            } 
        }
        return Observable.throw(error);
    }
```

This way the initial observable in quiz-edit-component receives the result of the second call to the Web API and the route to home is activated after the quiz data is updated.

**Comment by Darkseal** [comment]
Thank you @mattjones61 for this brilliant fix: I will add it to the GitHub repo in the upcoming push update, referencing you and this issue in the code.

**Comment by lorenzonet** [comment]
Has anyone tryed that fix  on Angular >=8?
I did some tweaks with so success, so the Refresh token is not working!

`  intercept(
    request: HttpRequest<any>,
    next: HttpHandler): Observable<HttpEvent<any>> {

    this.auth = this.injector.get(AuthService);
    var token = (this.auth.isLoggedIn()) ? this.auth.getAuth()!.token : null;
    if (token) {
      // save current request
      this.currentRequest = request;

      return next.handle(request)
        .pipe(
          tap((event: HttpEvent<any>) => {
            if (event instanceof HttpResponse) {
              // do nothing
            }
          },
          error => {
              return this.handleError(error, next)
            })
        );
    }
    else {
      return next.handle(request);
    }
  }

  handleError(err: any, next: HttpHandler) {
    if (err instanceof HttpErrorResponse) {
      if (err.status === 401) {
        // JWT token might be expired:
        // try to get a new one using refresh token
        console.log("Token expired. Attempting refresh...");

        //  ===[2018.01.05 FIX - BOOK UPDATE]===
        // store current request into a local variable
        var previousRequest = this.currentRequest;
       
        // thanks to @mattjones61 for the following code
        return this.auth.refreshToken().pipe(
          mergeMap((refreshed) => {
            var token = (this.auth.isLoggedIn()) ? this.auth.getAuth()!.token : null;
            if (token) {
              previousRequest = previousRequest.clone({
                setHeaders: { Authorization: `Bearer ${token}` }
              });
              console.log("header token reset");
            }
            return next.handle(previousRequest);
          }));
      }
    }
    return throwError(err);
  }
}
`
