### ISSUE TITLE
Chapter_05_Part01  - Error on deleting quiz

### ISSUE THREAD

**Issue by edusfc15** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#19]
Hello, 

there is a problem when deleting a quiz:

![capturar](https://user-images.githubusercontent.com/13476234/35441634-68bbadb6-028b-11e8-83cb-3552f4f370a6.PNG)

The quiz is deleted, but remains in the same route. 

seems that the problem is in the return of the quizcontroller delete action:

`return new OkResult();`

if we change to :

`return new NoContentResult()`

it fix the problem.

**Comment by Darkseal** [comment]
Hello and thank you for purchasing the book.

Your findings are correct, the earlier versions of the Angular 5 HttpClient expect a Json result by default - unless you specifically tell Angular not to expect JSON - and will throw a SyntaxError (actually a Json parse error) if there's an empty response body. 

Notice that such behaviour has been fixed on December 2017, so that the XhrBackend will attempt the JSON parse only if the response body is non-empty. Otherwise, the body is left as null:

https://github.com/angular/angular/issues/19502

Most recent versions of Angular (>= 2018) should be able to properly support the `OkResult()` : if you're using earlier builds, `NoContentResult()` is the way to go. 

That said, since the book recommends to use Angular 5.0.2 which is older than the fix, I'll flag this as a BOOK ERRATA and push your solution as a viable fix.

Thank you for your findings!
