### ISSUE TITLE
Angular CLI version

### ISSUE THREAD

**Issue by Sami-L** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#33]
Hi, 

I had took a walk around the Angular tendances on the net, and found that the way this project is made exposes to many limits since it is not using Angular CLI, most people exposing projects on github or other sites had enhanced their projects to use Angular CLI instead of Webpack.

I think it is time to do the same with this course, or at least publish simultaneously a second version using Angular CLI.

**Comment by Darkseal** [comment]
Hello there,

The "course" can't be upgraded because it's part of a published book, hence it has to resemble the code written in the book.

That said, as you might already know, Angular/CLI is natively supported by VS2017 starting from version 5.6 preview 6: if you create an **Angular** project, VS2017 will create a `/ClientApp/` folder with all the required stuff - including the `.angular-cli.json` configuration file.

Given that, most of the book's Chapter 1 (angular project setup) could be replaced by just creating a new Angular project with VS2017 5.6 and skip all the Webpack-related stuff. All the other chapters will still work without significative issues, as the webpack configuration file will be auto-generated using the settings specified in the `.angular-cli.json` file.
