### ISSUE TITLE
Can't manage to user Role Authorization filter on controllers method

### ISSUE THREAD

**Issue by JhonBehan** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#42]
Hi @Darkseal , thanks for the support in the beginning, i got the same issue as MammadK, i cant manage how to add roles based filter upon the contollers for role based authorization.
Let me explain a little better, for me is working fine the [Authorized] filter but not the [Authorized(Roles="Administrator")] i got the DB seeded right as you can see in the screen shots.
In the book i m greatly guided throught the creation of the registeredUser and the Administrator roles but after does't explain how to get use of those roles for protecting apps API! am i missing something. i really need this!
![users](https://user-images.githubusercontent.com/25555836/45024615-b882bb80-b039-11e8-9f25-9bb49d994c8e.PNG)
![usertoroles](https://user-images.githubusercontent.com/25555836/45024617-b9b3e880-b039-11e8-96c3-fae69c9d06a7.PNG)
![roles](https://user-images.githubusercontent.com/25555836/45024618-bae51580-b039-11e8-81e6-20427d175c72.PNG)

as MammadK says i tried to retrive information about the user in as an example the quiz controller here there i a screen shot and everything seems working fine here is the pic.
![gettingtheusersandroles](https://user-images.githubusercontent.com/25555836/45024624-bf113300-b039-11e8-9bdb-eed6686054dc.PNG)

Also i got one last question, roaming around the internet in the various stackoverflow or blogs i find that everyone is putting the policy or role data in the jwt token and then in the startup class somehow setting the built in authorize class to manage policy or roles, but instead can i in someway get the roles of the user based on his Id on the DB? so somehow i can get the roles of the user on the fly and check for right authorization role so i don t have to expose roles of the user to the public?
Well thanks for everything, hope i wrote something understandable!

**Comment by Darkseal** [comment]
Hello there and thank you for purchasing the book.

Regarding your first question, well, since you did your own research you should are probably aware that "roles" and role-based checks are a MS-only thing: they don't exists outside of it, since no one else implements or follows the `IPrincipal` pattern. In the "non-Microsoft" world, which now also includes .NET Core, whenever you want to check for the existence of a given claim you can simply query the claims collection for what you are looking for. Needless to say, you have to do that manually - in ASP.NET Core you can easily do that by using the new policy-based pattern, which works in a very similar fashion (just replace "roles" with "policy" and create your token Claims accordingly) and will probably be a great replacement for your specific needs:

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-2.1

However, if you still want (or need) to implement role-based checks, you can still do that by using the `RoleClaimType` and/or `RoleClaimTypeRetriever` properties of the [TokenValidationParameters](https://msdn.microsoft.com/en-us/library/system.identitymodel.tokens.tokenvalidationparameters(v=vs.114).aspx) class: to do that, just open the `Startup.cs` file (`ConfigureServices` method) of the **TestMakerFree** sample app and configure these properties accordingly. You'll basically have to define your "roles" claims name and/or how to retrieve it after token validation, depending if you want to put the "roles" claim in your token or not. This will also answer to your second question - if you don't want to put that claim within you token, just implement the `RoleClaimTypeRetriever` function: you can then perform your logic/queries from there. However, be wary that you could run into some (hopefully minimal) performance issues by doing that, since you'll be using a sync SQL query on every login/permission check.

If you need further assistance, you can either ask me here or take a look at this great article which explains everything I said (and other useful things) about this specific topic:

https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by JhonBehan** [comment]
Hey Thank you very much for the reply @Darkseal thanks for all the link i ll definitely check those out ended implementing a IAuthorizationRequirement and then injecting that in the startup.cs as  policy.Requirements.Add<CustomRequirement> checking for role or whatever requirement i want to implement. As you was saying got a couple of complains about performance drop that will cause but i like that i got full control over the whole process in this way.
Thank you very much again great book!

Momo
