### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by wmlockhart** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#7]
When I try to Build 'TestMakerFreeWebApp_UpdatedProject' I get the following errors:

Can't resolve 'bootswatch/flatly/bootstrap.css' in 'C:\code\TestMaker\TestMakerFreeWebApp_UpdatedProject'	

and

MSB3073	The command "node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js" exited with code 2.

Can you please advise how I can fix this issue. Thanks.

**Comment by HudsonHawk** [comment]
I encountered this same issue. The "bootswatch" package is missing from the dependencies in the "package.json" file. To fix you just need to modify your package.json file to include this dependency. I added it directly below my bootstrap dependency, so that it now looks like this:

...
"bootstrap": "3.3.7",
**"bootswatch": "3.3.7",**
...

Just make sure your bootswatch package version matches the bootstrap version. Afterwards you can run your "update-npm.bat" script and then your "update-webpack.bat" script to rebuild the vendors file.

**Comment by wmlockhart** [comment]
Thank you HudsonHawk. That worked for me too.

**Comment by Darkseal** [comment]
Repo updated accordingly (master branch). Thank you for your findings!

**Comment by Sami-L** [comment]
For me it builds even if bootswatch is not included in package.json but gives error on publish.
After added the line suggested by @HudsonHawk, now I can publish without issues.
