### ISSUE TITLE
Chapter_09 - Refresh Token loop

### ISSUE THREAD

**Issue by gamsterx** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#8]
Hi,
I´am running the code of chapter_09 and get an infinite loop of requests while testing the refresh token "feature". 

![console](https://user-images.githubusercontent.com/34918735/34415940-7c0ce7c8-ebf1-11e7-924d-a2d3abd2622d.PNG)

Maybe there is something wrong/missing within the **AuthResponseInterceptor** ?

**Comment by Belka383** [comment]
I have the same problem!

**Comment by Darkseal** [comment]
Hello and thank you for purchasing the book. 

I can confirm that there's a bug in that part of code. The issue is related to the `this.currentRequest` local variable being overwritten when the `token/auth` call is performed in order to refresh the token, thus causing an endless loop.

In order to fix that, open the `auth.response.interceptor.ts` file and replace this:

```
console.log("Token expired. Attempting refresh...");

this.auth.refreshToken()
    .subscribe(res => {
        if (res) {
            // refresh token successful
            console.log("refresh token successful");

            // re-submit the failed request
            var http = this.injector.get(HttpClient);

            //  ===[2018.01.05 FIX - BOOK UPDATE]===
            // cfr. https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/8
            http.request(previousRequest).subscribe(

[...]
```
with this (2 lines modified + comments):

```
console.log("Token expired. Attempting refresh...");

//  ===[2018.01.05 FIX - BOOK UPDATE]===
// cfr. https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/8
// store current request into a local variable
var previousRequest = this.currentRequest;

this.auth.refreshToken()
    .subscribe(res => {
        if (res) {
            // refresh token successful
            console.log("refresh token successful");

            // re-submit the failed request
            var http = this.injector.get(HttpClient);

            //  ===[2018.01.05 FIX - BOOK UPDATE]===
            // cfr. https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/8
            http.request(previousRequest).subscribe(

[...]
```

I will update the repo accordingly for **Chapter 09**, **Chapter 10** and **UpdatedProject**.

Thank you for reporting this and sorry for the inconvenience.
